# Generated by Django 6.0 on 2025-12-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_tag_post_category_notification_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='layout_preference',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
