from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('user/<int:user_id>/', views.user_home, name='user_home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('create/', views.create_post, name='create_post'),
    path('post/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('profile/', views.profile, name='profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('search/', views.search, name='search'),
    path('category/<int:category_id>/', views.category_view, name='category_view'),
    path('tag/<int:tag_id>/', views.tag_view, name='tag_view'),
    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),
    path('send_message/<int:user_id>/', views.send_message, name='send_message'),
    path('inbox/', views.inbox, name='inbox'),
    path('chats/', views.chat_sessions, name='chat_sessions'),
    path('chats/<int:user_id>/', views.chat_history, name='chat_history'),
    path('chats/<int:user_id>/send/', views.send_chat_message, name='send_chat_message'),
    path('notifications/', views.notifications, name='notifications'),
    path('report/', views.report_content, name='report_content'),
    path('toggle_theme/', views.toggle_theme, name='toggle_theme'),
    path('set_layout/', views.set_layout_preference, name='set_layout'),
    path('set_chat_layout/', views.set_chat_layout, name='set_chat_layout'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('handle_report/<int:report_id>/<str:action>/', views.handle_report, name='handle_report'),
    path('toggle_user_ban/<int:user_id>/', views.toggle_user_ban, name='toggle_user_ban'),
    path('toggle_user_mute/<int:user_id>/', views.toggle_user_mute, name='toggle_user_mute'),
    path('toggle_admin/<int:user_id>/', views.toggle_admin, name='toggle_admin'),
]